//CODE GENERATED BY CLAUDE PER LAB 5 INSTRUCTIONS
//MILAH AND XIMENA WROTE THE SPECS AND PROMPT FOR THE BLACKJACK GAME CODE

package lab03.lab5cards;


import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.layout.Pane;
import javafx.stage.Stage;

import java.io.File;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

public class BlackjackGame {
    private final Stage stage = new Stage();
    private final Pane pane = new Pane();
    private final Button hit = new Button("Hit");
    private final Button stand = new Button("Stand");
    private final Button playAgain = new Button("Play Again");
    private final Label result = new Label();

    private List<File> deck = new ArrayList<>();
    private final List<File> playerHand = new ArrayList<>();
    private final List<File> dealerHand = new ArrayList<>();

    // true after the dealer and player tie below 21: the player is forced to hit again
    private boolean mustHit = false;

    public BlackjackGame() {
        pane.setStyle("-fx-background-color: #00FF00");

        hit.setLayoutX(220);
        hit.setLayoutY(450);
        stand.setLayoutX(300);
        stand.setLayoutY(450);
        playAgain.setLayoutX(260);
        playAgain.setLayoutY(450);
        result.setLayoutX(270);
        result.setLayoutY(400);
        result.setStyle("-fx-font-size: 28px; -fx-font-weight: bold");

        pane.getChildren().addAll(hit, stand);

        hit.setOnAction(e -> hitPressed());
        stand.setOnAction(e -> standPressed());
        playAgain.setOnAction(e -> newGame());

        stage.setTitle("BlackJack!");
        stage.setScene(new Scene(pane, 600, 500));
    }

    public void show() {
        newGame();
        stage.show();
    }

    // Shuffles a fresh deck and deals two face-up cards each (player, dealer, player, dealer)
    private void newGame() {
        File[] files = new File("src/main/Cards").listFiles();
        if (files == null) {
            System.out.println("Could not find the Cards");
            return;
        }

        deck = new ArrayList<>();
        for (File f : files) {
            if (f.isFile() && f.getName().endsWith(".png")) {
                deck.add(f);
            }
        }
        Collections.shuffle(deck);

        playerHand.clear();
        dealerHand.clear();
        mustHit = false;

        playerHand.add(deck.remove(deck.size() - 1));
        dealerHand.add(deck.remove(deck.size() - 1));
        playerHand.add(deck.remove(deck.size() - 1));
        dealerHand.add(deck.remove(deck.size() - 1));

        pane.getChildren().removeAll(result, playAgain);
        hit.setVisible(true);
        stand.setVisible(true);
        stand.setDisable(false);
        redraw();

        int p = handValue(playerHand);
        int d = handValue(dealerHand);
        if (p == 21 && d == 21) {
            endGame("Win");      // both start with 21: the player wins
        } else if (d == 21) {
            endGame("Loss");     // dealer 21 on the deal
        } else if (p == 21) {
            endGame("Win");      // player 21 on the deal
        }
    }

    private void hitPressed() {
        playerHand.add(deck.remove(deck.size() - 1));
        redraw();

        int p = handValue(playerHand);
        if (p > 21) {
            endGame("Loss");
        } else if (p == 21) {
            endGame("Win");
        } else if (mustHit && p > handValue(dealerHand)) {
            // the forced hit put the player above the dealer
            endGame("Win");
        }
        // otherwise the totals are still equal, so the player must hit again
    }

    private void standPressed() {
        // dealer hits on 16 or lower, stands on 17 or higher
        while (handValue(dealerHand) <= 16) {
            dealerHand.add(deck.remove(deck.size() - 1));
        }
        redraw();

        int p = handValue(playerHand);
        int d = handValue(dealerHand);

        if (d > 21) {
            endGame("Win");
        } else if (d == 21) {
            endGame("Loss");
        } else if (d > p) {
            endGame("Loss");
        } else if (p > d) {
            endGame("Win");
        } else {
            // same value under 21: the player must hit again
            mustHit = true;
            stand.setDisable(true);
        }
    }

    private void endGame(String message) {
        hit.setVisible(false);
        stand.setVisible(false);
        result.setText(message);
        pane.getChildren().addAll(result, playAgain);
    }

    // Draws the dealer's cards on the top row and the player's cards on the bottom row
    private void redraw() {
        pane.getChildren().removeIf(node -> node instanceof ImageView);
        drawHand(dealerHand, 40);
        drawHand(playerHand, 220);
    }

    private void drawHand(List<File> hand, int y) {
        // squeeze the cards closer together if the hand gets long
        double step = hand.size() > 1 ? Math.min(80, 500.0 / (hand.size() - 1)) : 0;
        // total width of the row of cards, used to find the left edge that centers it in the 600-wide pane
        double rowWidth = 70 + (hand.size() - 1) * step;
        double startX = (600 - rowWidth) / 2;
        for (int i = 0; i < hand.size(); i++) {
            ImageView view = new ImageView(new Image(hand.get(i).toURI().toString()));
            view.setFitWidth(70);
            view.setFitHeight(95);
            view.setPreserveRatio(true);
            view.setLayoutX(startX + i * step);
            view.setLayoutY(y);
            pane.getChildren().add(view);
        }
    }

    // Total of a hand: each ace counts as 1, or 11 if that keeps the total at 21 or under
    private int handValue(List<File> hand) {
        int total = 0;
        int aces = 0;
        for (File card : hand) {
            int points = cardPoints(card);
            if (points == 1) {
                aces++;
            }
            total += points;
        }
        if (aces > 0 && total + 10 <= 21) {
            total += 10;
        }
        return total;
    }

    // Same file-name pattern as the rest of the project: ace is "1.png", face cards are named
    private int cardPoints(File card) {
        String name = card.getName();
        if (name.endsWith("Jack.png") || name.endsWith("Queen.png") || name.endsWith("King.png")) {
            return 10;
        }
        if (name.endsWith("10.png")) {
            return 10;
        }
        return Character.getNumericValue(name.charAt(name.length() - 5));
    }
}